AWSTemplateFormatVersion: "2010-09-09"
Description: Create private ECR repository

Parameters:
  ECRRepositoryName:
    Description: Your ECR Private Repository name
    Type: String
    Default: "ecr-ecs"

Resources:
  PrivateECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ECRRepositoryName
      RepositoryPolicyText:
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - "arn:aws:iam::250958575382:user/Pavel-Liakhouski"
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"

